# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='add_date',
            field=models.DateTimeField(verbose_name=b'Date'),
        ),
    ]
